repository:
  description: "Django REST Framework Web API テンプレート"
  has_wiki: false
  has_projects: false
  has_downloads: true
  default_branch: main
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  allow_auto_merge: true

labels:
  - name: bug
    color: "d73a4a"
    description: "Something isn't working"
  - name: feature
    color: "1a7f37"
    description: "New feature"
  - name: enhancement
    color: "a2eeef"
    description: "Improvements to existing features"
  - name: docs
    color: "a259ff"
    description: "Documentation"
  - name: ci
    color: "e3b341"
    description: "CI/CD changes"
  - name: refactor
    color: "ededed"
    description: "Code refactoring"
  - name: test
    color: "ededed"
    description: "Test changes"

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_status_checks:
        strict: true
        contexts:
          - ruff
          - fixit
          - mypy
          - ty
          - unit_test
          - functional_test
          - integration_test
          - commitlint
          - block-fixup-and-squash
      enforce_admins: true
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      restrictions: false
